[package]
name = "gens"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = { version = "0.16.0-dev", path = "../clone/bevy/crates/bevy_ecs", default-features = false }
disqualified = "1.0.0"
